"""Domain constants and configuration defaults."""

from decimal import Decimal

# Inventory
DEFAULT_SAFETY_STOCK_SERVICE_LEVEL = 0.95
DEFAULT_FORECAST_HORIZON_DAYS = 90
ALLOCATION_LOCK_TTL_SECONDS = 300
RESERVATION_TTL_MINUTES = 30
MAX_ALLOCATION_SPLIT_WAREHOUSES = 5

# Fulfillment
DEFAULT_ROUTING_STRATEGY = "cost_optimized"
MAX_ORDER_LINES = 500
MAX_QUANTITY_PER_LINE = 10000
PARTIAL_FULFILLMENT_ENABLED_DEFAULT = True

# Transportation
MAX_ROUTE_STOPS = 25
CONSOLIDATION_WINDOW_HOURS = 4
DEFAULT_SHIPPING_BASE_COST = Decimal("15.00")
MAX_SHIPMENT_WEIGHT_KG = Decimal("1000")

# Warehouse
DEFAULT_PICK_PRIORITY = 5
PUTAWAY_VELOCITY_ZONES = {"high": "A", "medium": "B", "low": "C"}
CYCLE_COUNT_VARIANCE_AUTO_ADJUST = 5
CYCLE_COUNT_VARIANCE_REVIEW = 50

# Procurement
DEFAULT_PO_PAYMENT_TERMS_DAYS = 30
MIN_SUPPLIER_QUALIFICATION_SCORE = 0.75
PREFERRED_SUPPLIER_THRESHOLD = 0.85
REPLENISHMENT_LEAD_TIME_BUFFER_DAYS = 3

# Optimization
OVERFLOW_CAPACITY_THRESHOLD_PCT = 90.0
OPTIMIZATION_ALGORITHM_VERSION = "2.1"

# Events
EVENT_STREAM_MAX_LENGTH = 100000
MAX_EVENT_RETRY_COUNT = 5
EVENT_BATCH_SIZE = 50

# Cache
CACHE_TTL_INVENTORY_SECONDS = 60
CACHE_TTL_ROUTING_SECONDS = 120
CACHE_TTL_FORECAST_SECONDS = 300

# Audit
AUDIT_RETENTION_DAYS = 2555

# API
API_VERSION = "v2"
CORRELATION_ID_HEADER = "X-Correlation-ID"

# Worker
WORKER_POLL_INTERVAL_MS = 500

# Batch processing
BATCH_ALLOCATION_SIZE = 25
BATCH_RECONCILIATION_PARALLEL = 4

# Network coordination
NETWORK_HEALTH_DEGRADED_THRESHOLD = 5
NETWORK_HEALTH_CRITICAL_THRESHOLD = 10

# Dependency graph
MAX_DEPENDENCY_DEPTH = 20
CYCLE_DETECTION_ENABLED = True
